### ISSUE TITLE
Support for snapshot versions

### ISSUE THREAD

**Issue by rrigoni** [JS-DevTools/npm-publish#202] opened 2024-06-14 17:26 UTC
Why this library throws the following error if I use any release different than `{major}.{minor}.{patch}`? Anything like `{major}.{minor}.{patch}-snapshot` or even `{major}.{minor}.{patch}.something` throws the following error: 

```
Run JS-DevTools/npm-publish@v2
  with:
    token: ***
    package: ./package.json
Error: InvalidPackageVersionError: Package version must be a string, got "undefined"
```
Happening with node 18 on github actions.

**Comment by mcous** [comment] 2024-06-14 18:19
Hi @rrigoni, it looks like you're not using the latest version of this action, which includes at least one important fix related to the version string: #161. Is this occurring in a public repository? If so, I'd be happy to take a look if you could provide me with a link.

This error occurs if your `package.json#version` field is not parsable by [node-semver](https://github.com/npm/node-semver). `semver.valid` allows "prerelease" versions, so I suspect something is likely wrong with your `package.json` file

```js
const semver = require("semver")

console.log('Valid?', semver.valid('1.2.3-snapshot'))
// Logs `Valid? 1.2.3-snapshot`
```

I recommend that you

- Update to the latest version (`v3`) of the action
- Double check that your `version` field in `package.json` is set correctly

**Comment by mcous** [comment] 2024-06-19 15:53
@rrigoni are you still having an issue here? I am unable to reproduce any issues with snapshot versions; my tests are showing successful publishing of prerelease packages

**Comment by mcous** [comment] 2024-06-27 23:21
Closing due to lack of reproduction or activity

**Closed by mcous** 2024-06-27 23:21 UTC
Labels: more info needed
