### ISSUE TITLE
Error: Input required and not supplied: token

### ISSUE THREAD

**Issue by lastdoctor** [JS-DevTools/npm-publish#31] opened 2021-01-31 18:58 UTC
Hi, I have problem
npm-publish.yml
`on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}`

and Here I have problem
`Run JS-DevTools/npm-publish@v1
  with:
    registry: https://registry.npmjs.org/
    package: package.json
    tag: latest
    dry-run: false
    check-version: true
Error: Error: Input required and not supplied: token
    at Object.getInput (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/node_modules/@actions/core/lib/core.js:94:1)
    at main (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/action/index.ts:17:14)
    at Object.48 (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/action/index.ts:74:1)
    at __webpack_require__ (/webpack/bootstrap:21:1)
    at startup (/webpack/bootstrap:40:1)
    at /webpack/bootstrap:44:1
    at Object.<anonymous> (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/dist/index.js:50:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)`

**Comment by trivikr** [comment] 2021-04-08 02:27
I'm receiving the same error.

Failed GitHub Action for reference: https://github.com/trivikr/test-postinstall-node-version-check/actions/runs/727995782

Error:

```console
Error: Error: Input required and not supplied: token
    at Object.getInput (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/node_modules/@actions/core/lib/core.js:94:1)
    at main (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/action/index.ts:17:14)
    at Object.48 (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/src/action/index.ts:74:1)
    at __webpack_require__ (/webpack/bootstrap:21:1)
    at startup (/webpack/bootstrap:40:1)
    at /webpack/bootstrap:44:1
    at Object.<anonymous> (/home/runner/work/_actions/JS-DevTools/npm-publish/v1/dist/index.js:50:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

Configuration for reference:
```yml
name: push

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: JS-DevTools/npm-publish@v1
        env:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

```

**Comment by ayush-goyal** [comment] 2021-04-13 06:54
I'm having this same issue as well ^

**Comment by Nurutomo** [comment] 2021-06-13 05:18
same error with this configuration
```yml
name: npm-publish
on: "workflow_dispatch"
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.0.0
    - id: publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
```

The Error Log:
https://github.com/Nurutomo/xteam-api/runs/2812373560?check_suite_focus=true

**Comment by thegiantbeast** [comment] 2022-03-15 11:02
The workaround I found to work is to run `env` as a step before this action. Like so:

```
    - name: List Github Actions
       run: env
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
```

It seems there's some race condition where the action tries to read `process.env`, but the variables were not yet set up? 🤔 
It sounds weird this explanation, but it's the closest thing I can think about

**Comment by thegiantbeast** [comment] 2022-03-15 11:03
@JamesMessinger any thoughts on this one? 🙇

**Comment by OskarDamkjaer** [comment] 2022-04-04 07:50
I ran into this issue as well, my problem was not setting the `environment` key properly, so my action didn't have access to the NPM_TOKEN, move info in the github action docs [here](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment ) 😄

**Comment by mcous** [comment] 2023-04-07 16:05
Hi all, these all look like various misconfiguration issues. I'm going to close this issue since links to various action run logs posted have expired so reproduction would be overly difficult. If anyone is still experiencing issues, please feel free to open a new issue!

If you're interested in seeing a working configuration for this action, you can take a look at: https://github.com/viamrobotics/prime/blob/main/.github/workflows/publish.yml

**Closed by mcous** 2023-04-07 16:05 UTC
Labels: question
