### ISSUE TITLE
Custom registry URL is truncated for token config

### ISSUE THREAD

**Issue by hermann-noll** [JS-DevTools/npm-publish#46] opened 2021-11-17 09:28 UTC
I had a problem where the action would fail with 403 when trying to push to a custom registry. I noticed that in the `.npmrc` the registry URL was truncated (so instead of `//some.domain/a/path/:_authToken=${INPUT_TOKEN}` there was `//some.domain/:_authToken=${INPUT_TOKEN}`).

With a small change in `npm-config.ts` to use the full URL the action succeeded without any further problems:
```typescript
  let authDomain = registry.href.slice(registry.protocol.length);
  if (!authDomain.endsWith("/"))
    authDomain += "/";
```

**Comment by mcous** [comment] 2023-04-10 15:28
I'm new to the codebase, but it appears stripping the path off the `registry` input to use only the origin for the auth block is intentional. Going off this snippet from the [npm auth docs](https://docs.npmjs.com/cli/v9/configuring-npm/npmrc#auth-related-configuration)...

> ```ini
> @myorg:registry=https://somewhere-else.com/myorg
> @another:registry=https://somewhere-else.com/another
>
> ; would apply to both @myorg and @another
> //somewhere-else.com/:_authToken=MYTOKEN
>
> ; would apply only to @myorg
> //somewhere-else.com/myorg/:_authToken=MYTOKEN1
>
> ; would apply only to @another
> //somewhere-else.com/another/:_authToken=MYTOKEN2
> ```

...an auth setting of `//example.com/:_authToken=ABC123` _will_ apply to to a registry setting of `registry=https://example.com/some/path/`. Is it possible your 403 errors were caused by something else?

Since this issue is quite old and I don't see any obvious bugs in the code, I'm going to close this as "cannot reproduce." Let me know if you are still encountering this 403 issue and we can investigate / re-open if necessary.

**Closed by mcous** 2023-04-10 15:28 UTC
Labels: question
