### ISSUE TITLE
Publish to a private registry authentication fails and work around

### ISSUE THREAD

**Issue by Dreamystify** [JS-DevTools/npm-publish#54] opened 2022-06-29 11:32 UTC
I tried to get this working with no success with auth issues:

`     npm ERR! 401 Unauthorized - GET https://<workspace>.bytesafe.dev/r/npm/@<scope-name>%2f<package-name> - Access Denied`
 
I require the step **Setup NPMrc for JS-DevTools** for the auth to work

```
 - name: Setup NPMrc for JS-DevTools
   run: echo "//<workspace>.bytesafe.dev/r/npm/:_authToken=${{secrets.BYTESAFE_TOKEN}}" >> .npmrc
 - id: publish
    uses: JS-DevTools/npm-publish@v1
    with:
      registry: 'https://<workspace>.bytesafe.dev/r/npm/'
      token: ${{secrets.BYTESAFE_TOKEN}}
      access: restricted
      check-version: true
  - if: steps.publish.outputs.type != 'none'
     run: |
       echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
```
Am I configuring **JS-DevTools/npm-publish@v1** wrong?

**Comment by mcous** [comment] 2023-04-10 15:13
In your example snippet, I am assuming you are using `<workspace>` as a placeholder to be replaced with your actual Bytesafe subdomain. 

My ideas:

> - name: Setup NPMrc for JS-DevTools
>  run: echo "//<workspace>.bytesafe.dev/r/npm/:_authToken=${{secrets.BYTESAFE_TOKEN}}" >> .npmrc

This above step should not be necessary when using this action

> - id: publish
>   uses: JS-DevTools/npm-publish@v1
>   with:
>     registry: 'https://<workspace>.bytesafe.dev/r/npm/'
>     token: ${{secrets.BYTESAFE_TOKEN}}
>     access: restricted
>     check-version: true

I think you must use spaces when accessing repository secrets via `${{ ... }}`. This is a GH Actions syntax thing, and not something specific to this action.

```
# correct
token: ${{ secrets.BYTESAFE_TOKEN }}

# incorrect
token: ${{secrets.BYTESAFE_TOKEN}}
```

Since this ticket is a little old and I don't see any issues in the code, I'm going to close this ticket as "cannot reproduce." Let me know if you're still experiencing issues and we can investigate and/or re-open.

**Closed by mcous** 2023-04-10 15:13 UTC
Labels: question
